spring:
  config:
    import: "classpath:values-dev.properties"
  cloud:
    vault:
      uri: ${HASHICORP_VAULT_URI}
      token: ${HASHICORP_VAULT_TOKEN}
      kv:
        enabled: true
        backend: jwt
        default-context: secret
